// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace thema12.Models
{
    public partial class Deadline
    {
        public int Deadline_ID { get; set; }
        public DateTime? Reminders { get; set; }
        public int DeadlineStatusID { get; set; }
        public int Task_ID { get; set; }
        [DisplayName("Deadline")]
        public DateTime Deadline1 { get; set; }

        public virtual DeadlineStatus DeadlineStatus { get; set; }
        public virtual Task Task { get; set; }
    }
}