// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace thema12.Models
{
    public partial class TaskStatus
    {
        public TaskStatus()
        {
            Tasks = new HashSet<Task>();
        }

        public int TaskStatusID { get; set; }
        public string TaskStatusName { get; set; }

        public virtual ICollection<Task> Tasks { get; set; }
    }
}