// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace thema12.Models
{
    public partial class Task
    {
        public Task()
        {
            InverseBlocker_Task = new HashSet<Task>();
        }

        public int Task_ID { get; set; }
        public int TaskStatusID { get; set; }
        public int Account_ID { get; set; }
        public int? Blocker_Task_ID { get; set; }

        [DisplayName("Task")]
        public string Task_Name { get; set; }

        public virtual Account Account { get; set; }
        public virtual Task Blocker_Task { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual Deadline Deadline { get; set; }
        public virtual ICollection<Task> InverseBlocker_Task { get; set; }
    }
}