// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace thema12.Models
{
    public partial class vTaskList
    {
        public int Task_ID { get; set; }
        public string TaskStatusName { get; set; }
        public string AccountName { get; set; }
    }
}